services:
  app:
    image: ${DOCKER_REGISTRY}/dashboard:${DOCKER_BRANCH}
    container_name: ${DOCKER_BRANCH}-dashboard
    environment:
      - THEGRAPH_API_KEY=$THEGRAPH_API_KEY
      - REALTOKEN_COMMUNITY_API_KEY=$REALTOKEN_COMMUNITY_API_KEY

      - REALTOKEN_COMMUNITY_API_BASE=$REALTOKEN_COMMUNITY_API_BASE
      - REALTOKEN_COMMUNITY_API_VERSION=$REALTOKEN_COMMUNITY_API_VERSION
      - REALTOKEN_COMMUNITY_API_GET_ALLTOKENS=$REALTOKEN_COMMUNITY_API_GET_ALLTOKENS
      - REALTOKEN_COMMUNITY_API_HISTORY_BASE=$REALTOKEN_COMMUNITY_API_HISTORY_BASE
      - PITSBI_API_BASE
      - PITSBI_API_VERSION
      - PITSBI_API_GET_LASTUPDATE
      - PITSBI_API_GET_ALLTOKENS
      - MATOMO_URL=$MATOMO_URL
      - MATOMO_SITE_ID=$MATOMO_SITE_ID
      - RPC_URLS_ETH_MAINNET=$RPC_URLS_ETH_MAINNET
      - RPC_URLS_GNOSIS_MAINNET=$RPC_URLS_GNOSIS_MAINNET
    networks:
      - traefik-realt
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard-${DOCKER_BRANCH}.rule=Host(`${HOSTNAME}`)'
      - 'traefik.http.routers.dashboard-${DOCKER_BRANCH}.entrypoints=websecure'
      - 'traefik.http.services.dashboard-${DOCKER_BRANCH}.loadbalancer.server.port=3000'
    restart: always

networks:
  traefik-realt:
    external: true
