export enum AssetSortType {
  NAME = 'name',
  VALUE = 'value',
  APR = 'apr',
  RENT = 'rent',
  RENT_START = 'rentStart',
  SUPPLY = 'supply',
  TOKEN = 'token',
  TOTAL_UNIT = 'totalUnit',
  RENTED_UNIT = 'rentedUnit',
  OCCUPANCY = 'occupancy',
  INITIAL_LAUNCH = 'initialLaunch',
  UNIT_PRICE_COST = 'unitPriceCost',
  UNREALIZED_CAPITAL_GAIN = 'unrealizedCapitalGain',
  LAST_CHANGE = 'lastChange',
}
